# Generated by Django 3.1.7 on 2021-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='autn',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='imsi',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='kasme',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='loginid',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rand',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='xres',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
