# Generated by Django 3.1.7 on 2021-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0002_auto_20210405_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='autn',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='imsi',
            field=models.CharField(default='11111 1111111111', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='kasme',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rand',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xres',
            field=models.CharField(default='11', max_length=200),
        ),
    ]
