# Generated by Django 3.1.7 on 2021-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0003_auto_20210420_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='amf',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='k',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='op',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='opc',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sqn',
            field=models.CharField(default='11', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='imsi',
            field=models.CharField(default='111111111111111', max_length=200),
        ),
    ]
